FROM ubuntu:precise
MAINTAINER Thomas Mohaupt "Thomas.Mohaupt@gmail.com"

ENV UPDATED_AT=2015-11-07

RUN apt-get update -qq

RUN apt-get -y install python-pip
RUN apt-get -y install python-dev
RUN apt-get -y remove inadyn

RUN pip install ansible

WORKDIR /data
